# ~/.config/starship/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"
add_newline = true

format = """
$directory\
$git_branch$git_status\
$golang$python$nodejs\
$terraform$docker_context\
$fill\
$kubernetes\
$aws\
$gcloud\
$line_break\
$character"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
style = "fg:crust bg:peach"
format = "[](fg:peach)[ $path ]($style)"
truncation_length = 5
truncate_to_repo = false

[git_branch]
symbol = ""
style = "fg:crust bg:yellow"
format = '[](fg:peach bg:yellow)[ $symbol $branch]($style)'

[git_status]
style = "fg:crust bg:yellow"
format = '[$all_status$ahead_behind ]($style)[](fg:yellow bg:green)'

[golang]
symbol = ""
style = "fg:crust bg:green"
format = '[ $symbol $version ]($style)[](fg:green)'

[python]
symbol = ""
style = "fg:crust bg:green"
format = '[ $symbol $version ]($style)[](fg:green)'

[nodejs]
symbol = "󰎙"
style = "fg:crust bg:green"
format = '[ $symbol $version ]($style)[](fg:green)'

[terraform]
symbol = "󱁢"
style = "fg:crust bg:lavender"
format = '[ $symbol $version ]($style)[](fg:lavender)'

# [docker_context]
# symbol = ""
# style = "fg:crust bg:lavender"
# format = '[ $symbol $context ]($style)[](fg:lavender)'

[kubernetes]
disabled = false
symbol = "󱃾"
style = "fg:crust bg:blue"
format = '[](fg:blue)[ $symbol $context( \($namespace\)) ]($style)'

[aws]
symbol = ""
style = "fg:crust bg:yellow"
format = '[](fg:yellow)[ $symbol $profile ]($style)'

[gcloud]
symbol = "󱇶"
style = "fg:crust bg:peach"
format = '[](fg:peach)[ $symbol $project ]($style)'

[fill]
symbol = " "

[line_break]
disabled = false

# Catppuccin Mocha palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[profiles]
transient = "[❯](bold green) "
rtransient = ''
